# Adjektivfortelling v1 
# This in Norwegian. It's a quite simple program out of some small game. It will present a story
# without certain words, which users are needed to put in before they hear the story. Usually end
# up in quite hilarious stories. Fun for kids. Home with corona so I try to make something out of my python 
# learning, which can also benefit my family here while we're in quaranteen. 
# 39 adjektiv

# For a version 2, there should be a randomizer out of lesser amount of adjektiv's. 39 is just too many to keep interest up.
# Let's do it pure first. This code gonna be very barebones and pure, not fancy at all. 

adj1 = input("Adjektiv 1: ")
adj2 = input("Adjektiv 2: ")
adj3 = input("Adjektiv 3: ")
adj4 = input("Adjektiv 4: ")
adj5 = input("Adjektiv 5: ")
adj6 = input("Adjektiv 6: ")
adj7 = input("Adjektiv 7: ")
adj8 = input("Adjektiv 8: ")
adj9 = input("Adjektiv 9: ")
adj10 = input("Adjektiv 10: ")
adj11 = input("Adjektiv 11: ")
adj12 = input("Adjektiv 12: ")
adj13 = input("Adjektiv 13: ")
adj14 = input("Adjektiv 14: ")
adj15 = input("Adjektiv 15: ")
adj16 = input("Adjektiv 16: ")
adj17 = input("Adjektiv 17: ")
adj18 = input("Adjektiv 18: ")
adj19 = input("Adjektiv 19: ")
adj20 = input("Adjektiv 20: ")
adj21 = input("Adjektiv 21: ")
adj22 = input("Adjektiv 22: ")
adj23 = input("Adjektiv 23: ")
adj24 = input("Adjektiv 24: ")
adj25 = input("Adjektiv 25: ")
adj26 = input("Adjektiv 26: ")
adj27 = input("Adjektiv 27: ")
adj28 = input("Adjektiv 28: ")
adj29 = input("Adjektiv 29: ")
adj30 = input("Adjektiv 30: ")
adj31 = input("Adjektiv 31: ")
adj32 = input("Adjektiv 32: ")
adj33 = input("Adjektiv 33: ")
adj34 = input("Adjektiv 34: ")
adj35 = input("Adjektiv 35: ")
adj36 = input("Adjektiv 36: ")
adj37 = input("Adjektiv 37: ")
adj38 = input("Adjektiv 38: ")
adj39 = input("Adjektiv 39: ")

print("")
print("Nå sitter vi ved det " + adj1 + " spisebordet til den " + adj2 + " familien til den " + adj3 + " Henrik. Han har")
print("invitert alle de " + adj4 + " vennene sine hit i dag bare fordi han fyller " + adj5 + " 10 år. Her sitter altså")
print("den " + adj6 + " Erik og han tror han er en " + adj7 + " gutt. Ved siden av han sitter den " + adj8 + " Andreas,")
print("og han liker godt den " + adj9 + " maten som den " + adj10 + " moren til Henrik har servert alle oss " + adj11)
print("klassekameratene. Så har vi den " + adj12 + " Aksel. Han er den aller " + adj13 + " gutten i dette " + adj14)
print("selskapet. Forresten tror den " + adj15 + " Adam at det er slik han er, men der tar han feil, for den")
print(adj16 + " Adam er " + adj17)
print("")
print("Den neste " + adj18 + " gutten er den " + adj19 + " Oliver. Han drikker den " + adj20 + " brusen han har i det")
print(adj21 + " glasset sitt. Forresten er han en " + adj22 + " gutt. Den " + adj23 + " læreren vår synes iallfall han er")
print(adj24 + " Nå må vi ikke glemme å beskrive den " + adj25 +  " Lasse. Alle de " + adj26 + " jentene i den " + adj27)
print("klassen vår sier han er en " + adj28 + " gutt. Nå ja, alle vi andre " + adj29 + " guttene synes jo ikke det, da!")
print("Den " + adj30 + " Pål er den " + adj31 + " skøyeren i dette " + adj32 + " selskapet. Han er jo så utrolig " + adj33)
print("Så er det den " + adj34 + " Nikolay. Han koser seg med den " + adj35 + "maten. Kanskje er det den " + adj36)
print("faren til det " + adj37 + " bursdagsbarnet som har funnet på at vi, de " + adj38 + " guttene som er her, skal")
print("spise dette " + adj39 + " måltidet.")
print("")

